CREATE TABLE USERS(
	ID_USER VARCHAR PRIMARY KEY,
	NAME_USER VARCHAR(50),
	SOBRENOME VARCHAR(50),
	AGE INTEGER CHECK (AGE> 0),
	GENDER VARCHAR(12)
);

CREATE TABLE RECIPES(
    ID_RECIPE VARCHAR PRIMARY KEY,
    TITLE VARCHAR(40) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PREP_TIME VARCHAR,
    USER_ID VARCHAR REFERENCES USERS(ID_USER)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    MODO_PREPARO TEXT NOT NULL
);

CREATE TABLE INGREDIENTS(
	ID_INGREDIENT VARCHAR PRIMARY KEY,
	NAME_INGREDIENT VARCHAR(50) NOT NULL,
	TYPE_INGREDIENT VARCHAR(20)
);

CREATE TABLE RECIPE_INGREDIENT(
	ID_RECIPE VARCHAR REFERENCES RECIPES(ID_RECIPE)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	ID_INGREDIENT VARCHAR REFERENCES INGREDIENTS(ID_INGREDIENT)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	QUANTITY INTEGER CHECK (QUANTITY >= 1),
	NOME_INGREDIENT VARCHAR,

	PRIMARY KEY(ID_RECIPE, ID_INGREDIENT)
);

